Guillaume
GuillaumePOT/OC-java-p2 pull request #1
Opened 2023-03-24 05:02 UTC by GuillaumePOT

PR before merge with the branch master.

2023-03-24 10:57 UTC, metaXIII requested changes
Do not hesitate to include .gitignore in order to avoid the .class available at each run

2023-03-24 10:57 UTC, metaXIII commented on com/hemebiotech/analytics/WriteSymptomDataToFile.java
> +  private final String fileOutput = "result.out";
no need for javadoc for this variables, javadoc is supposed to be existing only for method

2023-03-24 10:57 UTC, metaXIII commented on com/hemebiotech/analytics/ISymptomWriter.java
> +  public void writeSymptoms(Map<String, Integer> symptoms);
missing javadoc

2023-03-24 10:57 UTC, metaXIII commented on com/hemebiotech/analytics/AnalyticsCounter.java
> +  public void writeSymptoms(Map<String, Integer> symptoms) {
by consistency, do not hesitate to create javadoc here also

2023-03-24 10:57 UTC, metaXIII commented on com/hemebiotech/analytics/ReadSymptomDataFromFile.java
> +   *
missing global description (be careful with your dot on line 16)

2023-03-24 10:57 UTC, metaXIII commented on com/hemebiotech/analytics/WriteSymptomDataToFile.java
> +/**.
no need for the dot here on line 8

2023-03-28 16:21 UTC, GuillaumePOT commented
> 

Just modified what have been asked.

2023-03-29 11:22 UTC, metaXIII commented on com/hemebiotech/analytics/AnalyticsCounter.java
> +  public void writeSymptoms(Map<String, Integer> symptoms) {
missing @param symptoms Map<String, Integer> symptoms

2023-03-29 11:25 UTC, metaXIII commented on .gitignore
> +symptoms.txt
in order to test the program, include symptoms.txt to the PR

2023-03-30 10:29 UTC, merged